/* Autogenerated file. Do not edit manually. */

/* eslint-disable max-classes-per-file */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/consistent-type-imports */

/*
  Fuels version: 0.101.1
  Forc version: 0.68.2
  Fuel-Core version: 0.43.2
*/

import {
  Account,
  BigNumberish,
  BN,
  decompressBytecode,
  Script as __Script,
} from 'fuels';

export type ScriptTestInputs = [secret: BigNumberish];
export type ScriptTestOutput = boolean;

export type ScriptTestConfigurables = Partial<{
  SECRET_NUMBER: BigNumberish;
}>;

const abi = {
  "programType": "script",
  "specVersion": "1",
  "encodingVersion": "1",
  "concreteTypes": [
    {
      "type": "bool",
      "concreteTypeId": "b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903"
    },
    {
      "type": "u64",
      "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
    }
  ],
  "metadataTypes": [],
  "functions": [
    {
      "inputs": [
        {
          "name": "secret",
          "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        }
      ],
      "name": "main",
      "output": "b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903",
      "attributes": null
    }
  ],
  "loggedTypes": [
    {
      "logId": "1515152261580153489",
      "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
    }
  ],
  "messagesTypes": [],
  "configurables": [
    {
      "name": "SECRET_NUMBER",
      "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0",
      "offset": 1064
    }
  ]
};

const bytecode = decompressBytecode('H4sIAAAAAAAAA21Sz0sbQRR+satd6q9pi3SZIi4UJb0tVK9llzVktzE4/ghNqdsdiwWPIYjnPfbYFtp69NL75Najxx79E3JoC6ILOSgoHtJvdjcosQthMvO+9733vu/xnkN7RAZln2EXZznqH5VYv0+fiUxx2jPFb5xdl+zLF9S87o6I666BvHV+JoApucJXve1leiBqqhmnbFxUO7as2KY++Qkbztvi1WMCVgI7AYylsVFVPfsPdrvA/uIn9nDsB68dk0xtC3Ela8oSq8qS9ey+K0PHit6qyei1mopqaprVbXdmbcndF1RC7lhb0MjTtQaxhusubBKVZ3cS3mwRC3eSdyEjUVVJnEoWp+JhnDqPwOnIkFl4P0C/qNEp5/dOGf+piHV1n/zPnTm+FHMEwDHp2SyqUCnyiOY9Rl+Jpr+ZRLmexLh/SLyaEK91KU7xfqqG+ca5f6xjJWhvtlfILFeMI36OQjr/yqYD8H0H76tL0vxzA/6cu0tRSPjZFNWJoIXJ6ksUew7xC/R/xQb5c0V+/6a/ks1XwbEBjmWXUB/e0HB/L3V/MiUL8UPpwxv4I8Ps3sT8VhSrcfgzEflqsh2gfmgkM435ZH8z8+d+exP+ND647SZibxrJQlN7tEd8Cx55e+gVHvmqFaetKfg0Hac2g/6OrGQ1Pkov88bM7x3souoVMXjE4NGdnp/rnoELgGPA/QQHi/weYTefYIesxZKxHrkuPfYWoZPWGlpcuQOt+oVWt70MBnq3A4MWArwHLdJ7in7v6TecRnxGozJ1tEaO3mOtT86P/Bsv7ngJ/t2c/1O2K+AVsk5WxuWrstY9WlWjwsM8G8rFHpui7prAmIijjsv0rPyC6Vq7t/Ym831m7O/5yux7lMm/f7fZemgwBAAA');

export class ScriptTest extends __Script<ScriptTestInputs, ScriptTestOutput> {

  static readonly abi = abi;
  static readonly bytecode = bytecode;

  constructor(wallet: Account) {
    super(bytecode, abi, wallet);
  }
}
